### ISSUE TITLE
Can the Max Time in Macro Creator be set in Settings?

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQMacroCreator#10]
There's a LOT of times where I'll wake up and/or come back from work, and the DQ's been running on the same 1 DQ for HOURS. Today it was on DQ 144 and it was 11hrs into it.
Can we have something in Macro Settings that you can set the time you want and when you open CQMC it's set and not showing -1?
Like, normally, if I use MC directly, I'll set it for 180 seconds. So, when I use CQA, it can use that as well and not be running for 11hrs pulling my CPU. The other day I woke up, went to work, came back, went to sleep, woke up and there was less than 2hrs before the next DQ. So, it was running for 22hrs.
Obviously it would be GREAT if Alya added it her her version so that it's one less thing you need to change. I prefer your versions because you have a better "Select Best Heroes" set up. With her's I consider myself lucky if my selection is 5 heroes (Had a 1 once!)

**Comment by MatthieuBonne** [comment]
Today's commit (of both CQA and CQMC) should make you happy ! :)

**Comment by Vitae666** [comment]
W00T!!

**Comment by Vitae666** [comment]
uuuhhhhh........
Let me just start this with this part of the Settings.json file...You'll see why:

```
"doAutoLO": true,
"optAutoLO": 1,
"heroesToProm6": null
```

Ok, so, I open CQMC, type 180, it immediately saves to Settings.json. Yay!
Close CQMC, check Settings, it's still there. Yay!
```
"doAutoLO": true,
"optAutoLO": 1,
"calcTimeLimit": 180
```
But....wait...where's heroesToProm6?

Open CQA and check Settings
```
"doAutoLO": true,
"optAutoLO": 1,
"heroesToProm6": null
```
There it is! Wait...where the heck is calcTimeLimit?

Click Run DQ and let it do it's thing.
```
"doAutoLO": true,
"optAutoLO": 1,
"calcTimeLimit": 10
```
It's BACK!....awww shit....heroesToProm6 is gone again?!.....wait...the hell?.....calcTimeLimit is set to 10?

Open CQMC, shows 10 there as well.
Close/Restart CQA, heroesToProm6 is back, calcTimeLimit is gone.
Click Solve Dungeons heroesToProm6 is gone, calcTimeLimit is set to 10.
Open CQMC, shows 10 there as well.

The easy part, I think, is that CQA's AppSettings.cs doesn't have 
`public int? calcTimeLimit { get; set; }`
And CQMC's AppSettings.cs doesn't have
`public string[] heroesToProm6 { get; set; }`

But I can't figure out why DQ/Dung is setting it to 10.
There's this in Form1
```
        private void TimeLimit_ValueChanged(object sender, EventArgs e)
        {
            appSettings.calcTimeLimit = (int)timeLimit.Value;
            appSettings.saveSettings();
        }
```
But I don't see any point where timeLimit is being set to 10 in the code.
Unless it's in this bit
```
                int tmp = appSettings.calcTimeLimit ?? -1;
                timeLimit.Value = (decimal)tmp;
```
I mainly point that out because you have both calcTimeLimit and timeLimit (no capital T) through out the code, and have tmp defined with calcTimeLimit and then timeLimit.Value doing that decimal thing with tmp.
So, I dunno. Cause really, that whole thing confuses me.
And there's this in Form1.Designer
`            this.timeLimit.ValueChanged += new System.EventHandler(this.TimeLimit_ValueChanged);`
Which I guess nullifies my "private void" part.
Damned if I know.

Also, as a test, when heroesToProm6 was showing, I clicked "Save DQ Settings" but it didn't do anything. It only happens when I click DQ/Dung, which I kinda figured, but felt it worth checking just in case there was something else :)

**Comment by MatthieuBonne** [comment]
Sorry, forgot to commit latest AppSettings edit... Fixed in a few minutes
The 10sec comes from CQA auto-DQ ; it shouldn't auto-save in Settings.json, I'll fix that.

**Comment by Vitae666** [comment]
All good :)
Thank you!
