### ISSUE TITLE
Stop letting me know I'm trying to use more than 25 heroes :)

### ISSUE THREAD

**Issue by Vitae666** [MatthieuBonne/CQMacroCreator#9]
Some "Yeah yeah, I know I have more than 25 heroes running. Let me be!" setting?

**Comment by Vitae666** [comment]
So? Any chance we can have a thing in the setting where the popup about more than 25 heroes can be ignored? :)
Cause, for the record, it will freeze the app until you click it. And that kinda sucks when you're gone for the day ;-)

**Comment by MatthieuBonne** [comment]
Wish granted !

**Comment by Vitae666** [comment]
When you add something I ask for:
![image](https://user-images.githubusercontent.com/9310914/66451349-0da5b380-ea2a-11e9-8dd7-1f2878dd0af1.png)
LOL!
